version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8090:80" # Map container port 80 to host port 8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8091:8000" # Map container port 8000 to host port 8000
